### ISSUE TITLE
[ bug reports ] the bot has no response，deployed on vps

### ISSUE THREAD

**Issue by lsyyktv** [kalanakt/All-Url-Uploader#116]
Checklist

the bot has no response

**Screenshots**
![image](https://github.com/kalanakt/All-Url-Uploader/assets/39065858/46bc2ebd-b600-4308-92f8-d79fdc019bc6)
![image](https://github.com/kalanakt/All-Url-Uploader/assets/39065858/11b681c3-d041-4f32-9fec-70e1d55906c8)

 - OS: debian 11
 - Deploy In  VPS
 - Version v2.0.2

I have filled the sample_config.py with the correct value，I don't know what to do now

**Comment by lsyyktv** [comment]
> lsyyktv thanks for reporting an issue.
I have changed plugins to Uploader
But there is still no response
![image](https://github.com/kalanakt/All-Url-Uploader/assets/39065858/33d31628-5e29-43a4-a9ca-2a0324267c85)

**Comment by kalanakt** [comment]
check bot is live or not?, there no output.

**Comment by lsyyktv** [comment]
> check bot is live or not?, there's no output.

bot is live,but there's no output
