### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by shennusharmaji8** [kalanakt/All-Url-Uploader#14]
i am new to github and have no idea how to deploy it on heroku, i tried deploying it from your {easiest heroku Deploy}, but got message -

[ Item could not be created:
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy. ]
while deploying on heroku

**Comment by kalanakt** [comment]
Read Issue #3 Reply.

**Comment by shennusharmaji8** [comment]
Hye thanks, I solved this issue but, guess the bot isn't working. /start works, /help doesn't work it replies nothing.
Bot supports Spankbang - but when i paste the video url, it gives no response.
