### ISSUE TITLE
Error BOT_TOKEN

### ISSUE THREAD

**Issue by ferdiedix** [kalanakt/All-Url-Uploader#142]
its always say 

__main__ - ERROR - Please set BOT_TOKEN in config.py or as env var

 but i already set the BOT_TOKEN in config.py i run on vps
![image](https://github.com/ytdl-org/youtube-dl/assets/68693801/d2084162-b019-43a8-92e3-a005d7672e26)
![image](https://github.com/ytdl-org/youtube-dl/assets/68693801/a30b12b6-c5ba-4a10-bcbf-eaf4f81a06fa)

**Comment by kalanakt** [comment]
the method you using is wrong, create .env file then add value 

```.env
BOT_TOKEN=1234567890abcdefghij
API_ID=123456
API_HASH=1234567890qwertyklmnopqrst
OWNER_ID=12345
```

> ref [example](https://github.com/kalanakt/All-Url-Uploader/blob/main/.env.example)
