### ISSUE TITLE
heroku says"Item could not be created: We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy."

### ISSUE THREAD

**Issue by AethersKz** [kalanakt/All-Url-Uploader#3]
![Screenshot_20220204-041022_cropped](https://user-images.githubusercontent.com/96607644/152502914-7a12b2f7-6dbf-454f-8a16-d07160fa2f5e.png)

;(

**Comment by kalanakt** [comment]
Use Following Method;

1st flok repo
in your flocked repo --> readme.MD --> line 22 
replace your repo link for https://github.com/kalanakt/All-Url-Uploader

**Comment by AethersKz** [comment]
![Screenshot_20220206-015618_cropped](https://user-images.githubusercontent.com/96607644/152670816-06ec3060-65d0-48df-8c4f-be5350132229.png)

It worked for me, entering the link of my forked repository https://heroku.com/deploy?template= Link of your forked repository

https://heroku.com/deploy?template=https://github.com/AethersKz/All-Url-Uploader

👍
