### ISSUE TITLE
Ssl error for this links

### ISSUE THREAD

**Issue by niranjantechofficial** [kalanakt/All-Url-Uploader#34]
![Screenshot_2022-08-10-00-34-22-310_org telegram messenger](https://user-images.githubusercontent.com/61946705/183741073-cb21f6c0-fc46-4aaf-a828-124a88ce913d.jpg)

I need download support for this urls
.. What is solution for this error

**Comment by kalanakt** [comment]
**working on it**

_this happens when web site not secure, which means no support for https_

**Dev Tasks**

- [ ] fix error
- [ ] download over `https://classplusapp.com/`

**Comment by niranjantechofficial** [comment]
But my link was have https connection.... And that bot shows ssl error how to fix now on that bot

**Comment by kalanakt** [comment]
maybe, 
that link was not a direct video link [try to send a direct link]. I can see in the link, it's not a public link (it needs to be authorized)

**Comment by niranjantechofficial** [comment]
Can you once dm on Tg @niranjantech

**Comment by kalanakt** [comment]
not direct link 👎🏻

**Comment by niranjantechofficial** [comment]
Brother it was supporting by 1 url bot on telegram... But i need my own bot... Help me to fix this issue
