### ISSUE TITLE
request

### ISSUE THREAD

**Issue by bulanbintang69** [kalanakt/All-Url-Uploader#4]
request the set caption feature and the upload mode feature, "like uploading in the form of documents or video streaming"
![IMG_20220216_134528](https://user-images.githubusercontent.com/87313549/154212037-cd9fac84-90bf-4532-8372-b86bcc32c1b9.jpg)

**Comment by bulanbintang69** [comment]
![IMG_20220216_134621](https://user-images.githubusercontent.com/87313549/154239343-e17df755-b035-4375-ba76-6d17f7408684.jpg)

**Comment by kalanakt** [comment]
updated ✔
