### ISSUE TITLE
AttributeError: type object 'Config' has no attribute 'DOWNLOAD_LOCATION'

### ISSUE THREAD

**Issue by irabro1992** [kalanakt/All-Url-Uploader#9]
any idea with this error ? please

root@ubuntu-8gb-hel1-1:~/All-Url-Uploader# python3 bot.py
Traceback (most recent call last):
  File "bot.py", line 26, in <module>
    if not os.path.isdir(Config.DOWNLOAD_LOCATION):
AttributeError: type object 'Config' has no attribute 'DOWNLOAD_LOCATION'

**Comment by kalanakt** [comment]
leave DOWNLOAD_LOCATION in reveal config vars
or
change it to ./DOWNLOADS

**Comment by irabro1992** [comment]
> leave DOWNLOAD_LOCATION in reveal config vars or change it to ./DOWNLOADS

![1](https://user-images.githubusercontent.com/73217997/173378283-b8b44658-d97e-48a1-ab8e-a531f3db414a.jpg)

this is how i set in sample_config.
do i need to do some changes ?

**Comment by kalanakt** [comment]
try now :)

**Comment by irabro1992** [comment]
> try now :)

![2](https://user-images.githubusercontent.com/73217997/173396830-ddad4db1-df7b-4e2b-a3f1-fa9800905b3d.jpg)

hi , deleted the previous cloned repo and recloned the repo. still the same error.

![3](https://user-images.githubusercontent.com/73217997/173397102-89b3c836-f298-45ef-b60a-b7238437e7c0.jpg)
